// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// lm_iv_rcpp
List lm_iv_rcpp(const arma::mat& X, const arma::colvec& Y, const arma::mat& Z);
RcppExport SEXP tidymodelR_lm_iv_rcpp(SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(lm_iv_rcpp(X, Y, Z));
    return rcpp_result_gen;
END_RCPP
}
// lm_rcpp
List lm_rcpp(const arma::mat& X, const arma::colvec& y);
RcppExport SEXP tidymodelR_lm_rcpp(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(lm_rcpp(X, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"tidymodelR_lm_iv_rcpp", (DL_FUNC) &tidymodelR_lm_iv_rcpp, 3},
    {"tidymodelR_lm_rcpp", (DL_FUNC) &tidymodelR_lm_rcpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_tidymodelR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
