# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lm_rcpp <- function(X, y) {
    .Call(tidymodelR_lm_rcpp, X, y)
}

lm_iv_rcpp <- function(X, Y, Z) {
    .Call(tidymodelR_lm_iv_rcpp, X, Y, Z)
}

